name: Release and Deploy React App

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  release-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository with full history
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # 4️⃣ Configure Git identity
      - name: Configure Git
        run: |
          git config --global user.name  "Gagandeep Singh"
          git config --global user.email "sgagandeep07@gmail.com"

      # 5️⃣ Bump version & generate CHANGELOG.md
      - name: Bump version & generate changelog
        run: npx standard-version

      # 6️⃣ Push version bump and tags
      - name: Push version bump and tags
        run: |
          git push origin refs/heads/main --follow-tags

      # 7️⃣ Get latest tag created
      - name: Get latest tag
        id: get_tag
        run: echo "LATEST_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      # 8️⃣ Build React app
      - name: Build React app
        run: npm run build

      # 9️⃣ Deploy to GitHub Pages (gh-pages branch)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          user_name: "Gagandeep Singh"
          user_email: "sgagandeep07@gmail.com"
          publish_branch: gh-pages

      # 🔟 Create GitHub Release
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.LATEST_TAG }}
          generateReleaseNotes: true
