name: Release and Deploy React App

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write # allow pushing commits/tags + creating releases
  pages: write # only needed if you also use the official Pages deploy action
  id-token: write

jobs:
  release-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository with full history
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # 4️⃣ Configure Git identity
      - name: Configure Git
        run: |
          git config --global user.name  "Gagandeep Singh"
          git config --global user.email "sgagandeep07@gmail.com"

      # 5️⃣ Bump version & generate CHANGELOG.md
      - name: Bump version & generate changelog
        run: npx standard-version

      # 6️⃣ Push version bump and tags
      - name: Push version bump and tags
        run: |
          git pull --rebase origin main
          git push origin main --follow-tags

      # 7️⃣ Build React app
      - name: Build React app
        run: npm run build

      # 8️⃣ Deploy to GitHub Pages (root)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          user_name: "Gagandeep Singh"
          user_email: "sgagandeep07@gmail.com"
          destination_dir: ""

      # 9️⃣ Create GitHub Release
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          generateReleaseNotes: true
